"""Shared data-type / function / query matrices used by scenario generators.

These lists are the source material that the generators expand into thousands of
scenarios (type x operation, function x usage, query-pattern x ORM, etc.).
"""

from __future__ import annotations

import itertools
import threading

# ---------------------------------------------------------------------------
# Unique-name generator (thread-safe, monotonic) so concurrent generators never
# collide on table/column names.
# ---------------------------------------------------------------------------
_lock = threading.Lock()
_counter = itertools.count(1)


def uname(prefix: str = "t") -> str:
    with _lock:
        n = next(_counter)
    return f"{prefix}_{n:06d}"


# ---------------------------------------------------------------------------
# DATA TYPES.  Each entry: (label, sql_type, sample_value, is_quoted)
#   sample_value is a python-side literal we render into SQL for the generic
#   declare/insert/roundtrip matrix. is_quoted controls SQL quoting.
# ---------------------------------------------------------------------------
TYPES: list[tuple[str, str, str, bool]] = [
    # integers
    ("tinyint", "TINYINT", "42", False),
    ("smallint", "SMALLINT", "1234", False),
    ("mediumint", "MEDIUMINT", "123456", False),
    ("int", "INT", "2000000000", False),
    ("int_unsigned", "INT UNSIGNED", "4000000000", False),
    ("bigint", "BIGINT", "9000000000000000000", False),
    ("bigint_unsigned", "BIGINT UNSIGNED", "18000000000000000000", False),
    ("bool", "BOOL", "1", False),
    ("bit8", "BIT(8)", "b'10101010'", False),
    # fixed / floating point
    ("decimal_10_2", "DECIMAL(10,2)", "12345.67", False),
    ("decimal_38_10", "DECIMAL(38,10)", "1234567890.1234567890", False),
    ("numeric_8_3", "NUMERIC(8,3)", "12345.678", False),
    ("float_p", "FLOAT(10,4)", "3.5", False),
    ("float_bare", "FLOAT", "3.5", False),  # known: rounds 3.5 -> 4.0
    ("double", "DOUBLE", "2.718281828459045", False),
    ("double_p", "DOUBLE(15,8)", "3.14159265", False),
    # strings
    ("char10", "CHAR(10)", "abcdef", True),
    ("varchar64", "VARCHAR(64)", "hello world", True),
    ("varchar255", "VARCHAR(255)", "the quick brown fox", True),
    ("binary8", "BINARY(8)", "abcd", True),
    ("varbinary32", "VARBINARY(32)", "binarydata", True),
    ("tinytext", "TINYTEXT", "tiny text value", True),
    ("text", "TEXT", "a longer text value for the column", True),
    ("mediumtext", "MEDIUMTEXT", "medium text", True),
    ("longtext", "LONGTEXT", "long text value", True),
    ("tinyblob", "TINYBLOB", "blobdata", True),
    ("blob", "BLOB", "blob value", True),
    ("mediumblob", "MEDIUMBLOB", "medium blob", True),
    ("longblob", "LONGBLOB", "long blob", True),
    # enum / set
    ("enum", "ENUM('a','b','c')", "b", True),
    ("set", "SET('x','y','z')", "x,y", True),
    # temporal
    ("date", "DATE", "2026-06-23", True),
    ("time", "TIME", "11:22:33", True),
    ("datetime", "DATETIME", "2026-06-23 11:22:33", True),
    ("datetime6", "DATETIME(6)", "2026-06-23 11:22:33.123456", True),
    ("timestamp", "TIMESTAMP", "2026-06-23 11:22:33", True),
    ("year", "YEAR", "2026", False),
    # json
    ("json", "JSON", '{"k": 1, "arr": [1,2,3]}', True),
    # uuid (known driver/type quirks)
    ("uuid", "UUID", "00000000-0000-0000-0000-000000000001", True),
    # matrixone vector types
    ("vecf32", "VECF32(3)", "[1,2,3]", True),
    ("vecf64", "VECF64(3)", "[1.5,2.5,3.5]", True),
    # --- additional size / precision / signedness variants ---
    ("tinyint_unsigned", "TINYINT UNSIGNED", "200", False),
    ("smallint_unsigned", "SMALLINT UNSIGNED", "60000", False),
    ("mediumint_unsigned", "MEDIUMINT UNSIGNED", "16000000", False),
    ("tinyint_zerofill", "TINYINT ZEROFILL", "7", False),
    ("int_zerofill", "INT ZEROFILL", "42", False),
    ("decimal_5_0", "DECIMAL(5,0)", "12345", False),
    ("decimal_18_4", "DECIMAL(18,4)", "12345678.9012", False),
    ("decimal_65_30", "DECIMAL(65,30)", "1.5", False),
    ("numeric_default", "NUMERIC", "42", False),
    ("dec_alias", "DEC(8,2)", "100.50", False),
    ("fixed_alias", "FIXED(8,2)", "100.50", False),
    ("float_24", "FLOAT(24)", "3.5", False),
    ("real_type", "REAL", "2.5", False),
    ("char_1", "CHAR(1)", "a", True),
    ("char_255", "CHAR(255)", "x", True),
    ("varchar_1", "VARCHAR(1)", "a", True),
    ("varchar_1000", "VARCHAR(1000)", "long varchar", True),
    ("varchar_16383", "VARCHAR(16383)", "wide varchar", True),
    ("binary_1", "BINARY(1)", "a", True),
    ("binary_255", "BINARY(255)", "x", True),
    ("varbinary_255", "VARBINARY(255)", "vbin", True),
    ("nchar", "NCHAR(10)", "abc", True),
    ("nvarchar", "NVARCHAR(20)", "abc", True),
    ("bit_1", "BIT(1)", "b'1'", False),
    ("bit_16", "BIT(16)", "b'1010101010101010'", False),
    ("bit_64", "BIT(64)", "b'1'", False),
    ("bool_alias", "BOOLEAN", "1", False),
    ("serial_type", "INT", "1", False),
    ("time_3", "TIME(3)", "11:22:33.123", True),
    ("time_6", "TIME(6)", "11:22:33.123456", True),
    ("timestamp_3", "TIMESTAMP(3)", "2026-06-23 11:22:33.123", True),
    ("timestamp_6", "TIMESTAMP(6)", "2026-06-23 11:22:33.123456", True),
    ("datetime_3", "DATETIME(3)", "2026-06-23 11:22:33.123", True),
    ("enum_many", "ENUM('a','b','c','d','e','f','g')", "d", True),
    ("set_many", "SET('a','b','c','d','e')", "a,c,e", True),
]

# Numeric types for boundary tests: (label, sql_type, min_val, max_val)
NUMERIC_BOUNDS: list[tuple[str, str, str, str]] = [
    ("tinyint", "TINYINT", "-128", "127"),
    ("tinyint_unsigned", "TINYINT UNSIGNED", "0", "255"),
    ("smallint", "SMALLINT", "-32768", "32767"),
    ("smallint_unsigned", "SMALLINT UNSIGNED", "0", "65535"),
    ("mediumint", "MEDIUMINT", "-8388608", "8388607"),
    ("int", "INT", "-2147483648", "2147483647"),
    ("int_unsigned", "INT UNSIGNED", "0", "4294967295"),
    ("bigint", "BIGINT", "-9223372036854775808", "9223372036854775807"),
    ("bigint_unsigned", "BIGINT UNSIGNED", "0", "18446744073709551615"),
    ("decimal_10_2", "DECIMAL(10,2)", "-99999999.99", "99999999.99"),
]

# Subset of types that participate in the heavier per-operation matrix (keeps the
# count high without blowing up to absurd numbers). Excludes types that can't be
# indexed/grouped meaningfully (TEXT/BLOB without length, JSON, vectors).
INDEXABLE_TYPES = [
    t for t in TYPES
    if t[0] in {
        "tinyint", "smallint", "int", "bigint", "decimal_10_2", "double",
        "char10", "varchar64", "varchar255", "date", "datetime", "time",
        "year", "enum",
        # additional variants
        "tinyint_unsigned", "smallint_unsigned", "mediumint_unsigned",
        "decimal_5_0", "decimal_18_4", "float_24", "real_type",
        "char_1", "char_255", "varchar_1", "varchar_1000",
        "nchar", "nvarchar", "bool_alias", "time_3", "timestamp_3",
        "datetime_3", "enum_many",
    }
]


# ---------------------------------------------------------------------------
# FUNCTIONS.  Each: (label, expression_using_args, in_where_expr_fmt, group)
#   expression_using_args  -> bare SELECT form
#   The generator builds {bare call, in-where, in-select-with-column} variants.
# ---------------------------------------------------------------------------
FUNCTIONS: list[tuple[str, str, str]] = [
    # --- string ---
    ("concat", "CONCAT('a','b','c')", "string"),
    ("concat_ws", "CONCAT_WS('-','a','b')", "string"),
    ("length", "LENGTH('hello')", "string"),
    ("char_length", "CHAR_LENGTH('héllo')", "string"),
    ("character_length", "CHARACTER_LENGTH('hi')", "string"),
    ("octet_length", "OCTET_LENGTH('hi')", "string"),
    ("upper", "UPPER('abc')", "string"),
    ("lower", "LOWER('ABC')", "string"),
    ("substring", "SUBSTRING('abcdef',2,3)", "string"),
    ("substr", "SUBSTR('abcdef',2)", "string"),
    ("left", "LEFT('abcdef',3)", "string"),
    ("right", "RIGHT('abcdef',3)", "string"),
    ("trim", "TRIM('  x  ')", "string"),
    ("ltrim", "LTRIM('  x')", "string"),
    ("rtrim", "RTRIM('x  ')", "string"),
    ("replace", "REPLACE('aXbXc','X','-')", "string"),
    ("reverse", "REVERSE('abc')", "string"),
    ("repeat", "REPEAT('ab',3)", "string"),
    ("lpad", "LPAD('5',3,'0')", "string"),
    ("rpad", "RPAD('5',3,'0')", "string"),
    ("locate", "LOCATE('c','abcdef')", "string"),
    ("position", "POSITION('c' IN 'abcdef')", "string"),
    ("instr", "INSTR('abcdef','c')", "string"),
    ("field", "FIELD('b','a','b','c')", "string"),
    ("elt", "ELT(2,'a','b','c')", "string"),
    ("insert_fn", "INSERT('abcdef',2,3,'XY')", "string"),
    ("ascii", "ASCII('A')", "string"),
    ("ord", "ORD('A')", "string"),
    ("char_fn", "CHAR(65,66,67)", "string"),
    ("hex", "HEX(255)", "string"),
    ("unhex", "UNHEX('414243')", "string"),
    ("bin", "BIN(10)", "string"),
    ("oct", "OCT(64)", "string"),
    ("conv", "CONV('FF',16,10)", "string"),
    ("soundex", "SOUNDEX('Robert')", "string"),
    ("quote", "QUOTE('a''b')", "string"),
    ("space", "SPACE(3)", "string"),
    ("strcmp", "STRCMP('a','b')", "string"),
    ("format", "FORMAT(1234.5678,2)", "string"),
    ("to_base64", "TO_BASE64('abc')", "string"),
    ("from_base64", "FROM_BASE64('YWJj')", "string"),
    ("md5", "MD5('abc')", "string"),
    ("sha", "SHA('abc')", "string"),
    ("sha1", "SHA1('abc')", "string"),
    ("sha2", "SHA2('abc',256)", "string"),
    ("crc32", "CRC32('abc')", "string"),
    ("regexp_like", "REGEXP_LIKE('abc','b')", "string"),
    ("regexp_substr", "REGEXP_SUBSTR('abcdef','c.e')", "string"),
    ("regexp_replace", "REGEXP_REPLACE('abc','b','X')", "string"),
    ("regexp_instr", "REGEXP_INSTR('abcdef','c')", "string"),
    # --- numeric / math ---
    ("abs", "ABS(-5)", "math"),
    ("ceil", "CEIL(4.2)", "math"),
    ("ceiling", "CEILING(4.2)", "math"),
    ("floor", "FLOOR(4.8)", "math"),
    ("round", "ROUND(3.14159,2)", "math"),
    ("truncate", "TRUNCATE(3.14159,2)", "math"),
    ("mod", "MOD(10,3)", "math"),
    ("power", "POWER(2,10)", "math"),
    ("pow", "POW(2,8)", "math"),
    ("sqrt", "SQRT(16)", "math"),
    ("exp", "EXP(1)", "math"),
    ("ln", "LN(2.718281828)", "math"),
    ("log", "LOG(2.718281828)", "math"),
    ("log2", "LOG2(8)", "math"),
    ("log10", "LOG10(1000)", "math"),
    ("sin", "SIN(0)", "math"),
    ("cos", "COS(0)", "math"),
    ("tan", "TAN(0)", "math"),
    ("asin", "ASIN(0)", "math"),
    ("acos", "ACOS(1)", "math"),
    ("atan", "ATAN(1)", "math"),
    ("atan2", "ATAN2(1,1)", "math"),
    ("cot", "COT(1)", "math"),
    ("pi", "PI()", "math"),
    ("degrees", "DEGREES(3.14159)", "math"),
    ("radians", "RADIANS(180)", "math"),
    ("sign", "SIGN(-7)", "math"),
    ("rand", "RAND()", "math"),
    ("rand_seed", "RAND(42)", "math"),
    ("least", "LEAST(3,1,2)", "math"),
    ("greatest", "GREATEST(3,1,2)", "math"),
    ("bit_count", "BIT_COUNT(255)", "math"),
    # --- date / time ---
    ("now", "NOW()", "datetime"),
    ("curdate", "CURDATE()", "datetime"),
    ("curtime", "CURTIME()", "datetime"),
    ("current_timestamp", "CURRENT_TIMESTAMP()", "datetime"),
    ("utc_date", "UTC_DATE()", "datetime"),
    ("utc_time", "UTC_TIME()", "datetime"),
    ("utc_timestamp", "UTC_TIMESTAMP()", "datetime"),
    ("unix_timestamp", "UNIX_TIMESTAMP('2026-06-23 00:00:00')", "datetime"),
    ("from_unixtime", "FROM_UNIXTIME(1750636800)", "datetime"),
    ("date_fn", "DATE('2026-06-23 11:22:33')", "datetime"),
    ("time_fn", "TIME('2026-06-23 11:22:33')", "datetime"),
    ("year_fn", "YEAR('2026-06-23')", "datetime"),
    ("quarter", "QUARTER('2026-06-23')", "datetime"),
    ("month", "MONTH('2026-06-23')", "datetime"),
    ("monthname", "MONTHNAME('2026-06-23')", "datetime"),
    ("week", "WEEK('2026-06-23')", "datetime"),
    ("weekofyear", "WEEKOFYEAR('2026-06-23')", "datetime"),
    ("day", "DAY('2026-06-23')", "datetime"),
    ("dayofmonth", "DAYOFMONTH('2026-06-23')", "datetime"),
    ("dayofweek", "DAYOFWEEK('2026-06-23')", "datetime"),
    ("dayofyear", "DAYOFYEAR('2026-06-23')", "datetime"),
    ("dayname", "DAYNAME('2026-06-23')", "datetime"),
    ("hour", "HOUR('11:22:33')", "datetime"),
    ("minute", "MINUTE('11:22:33')", "datetime"),
    ("second", "SECOND('11:22:33')", "datetime"),
    ("microsecond", "MICROSECOND('11:22:33.123456')", "datetime"),
    ("last_day", "LAST_DAY('2026-06-23')", "datetime"),
    ("date_add", "DATE_ADD('2026-06-23', INTERVAL 1 DAY)", "datetime"),
    ("date_sub", "DATE_SUB('2026-06-23', INTERVAL 1 MONTH)", "datetime"),
    ("adddate", "ADDDATE('2026-06-23', 7)", "datetime"),
    ("subdate", "SUBDATE('2026-06-23', 7)", "datetime"),
    ("datediff", "DATEDIFF('2026-06-23','2026-06-01')", "datetime"),
    ("timediff", "TIMEDIFF('11:22:33','10:00:00')", "datetime"),
    ("timestampdiff", "TIMESTAMPDIFF(DAY,'2026-06-01','2026-06-23')", "datetime"),
    ("timestampadd", "TIMESTAMPADD(DAY,7,'2026-06-23')", "datetime"),
    ("date_format", "DATE_FORMAT('2026-06-23','%Y/%m/%d')", "datetime"),
    ("str_to_date", "STR_TO_DATE('23/06/2026','%d/%m/%Y')", "datetime"),
    ("sec_to_time", "SEC_TO_TIME(3661)", "datetime"),
    ("time_to_sec", "TIME_TO_SEC('01:01:01')", "datetime"),
    ("to_days", "TO_DAYS('2026-06-23')", "datetime"),
    ("from_days", "FROM_DAYS(700000)", "datetime"),
    ("makedate", "MAKEDATE(2026,174)", "datetime"),
    ("maketime", "MAKETIME(11,22,33)", "datetime"),
    ("period_add", "PERIOD_ADD(202601,3)", "datetime"),
    ("period_diff", "PERIOD_DIFF(202606,202601)", "datetime"),
    ("extract", "EXTRACT(YEAR FROM '2026-06-23')", "datetime"),
    ("addtime", "ADDTIME('11:00:00','01:00:00')", "datetime"),
    ("subtime", "SUBTIME('11:00:00','01:00:00')", "datetime"),
    ("convert_tz", "CONVERT_TZ('2026-06-23 12:00:00','+00:00','+08:00')", "datetime"),
    # --- control / null ---
    ("if_fn", "IF(1=1,'y','n')", "control"),
    ("ifnull", "IFNULL(NULL,'x')", "control"),
    ("nullif", "NULLIF(1,1)", "control"),
    ("coalesce", "COALESCE(NULL,NULL,'z')", "control"),
    ("isnull", "ISNULL(NULL)", "control"),
    ("case_simple", "CASE 1 WHEN 1 THEN 'a' ELSE 'b' END", "control"),
    ("case_searched", "CASE WHEN 1>0 THEN 'p' ELSE 'q' END", "control"),
    # --- cast / convert ---
    ("cast_signed", "CAST('123' AS SIGNED)", "cast"),
    ("cast_unsigned", "CAST('123' AS UNSIGNED)", "cast"),
    ("cast_decimal", "CAST('1.5' AS DECIMAL(10,2))", "cast"),
    ("cast_char", "CAST(123 AS CHAR)", "cast"),
    ("cast_date", "CAST('2026-06-23' AS DATE)", "cast"),
    ("cast_datetime", "CAST('2026-06-23 1:2:3' AS DATETIME)", "cast"),
    ("convert_signed", "CONVERT('42', SIGNED)", "cast"),
    # --- json (many unimplemented) ---
    ("json_extract", """JSON_EXTRACT('{"a":1}','$.a')""", "json"),
    ("json_unquote", """JSON_UNQUOTE('"abc"')""", "json"),
    ("json_object", "JSON_OBJECT('a',1,'b',2)", "json"),
    ("json_array", "JSON_ARRAY(1,2,3)", "json"),
    ("json_valid", """JSON_VALID('{"a":1}')""", "json"),
    ("json_type", """JSON_TYPE('[1,2]')""", "json"),
    ("json_length", """JSON_LENGTH('[1,2,3]')""", "json"),
    ("json_keys", """JSON_KEYS('{"a":1,"b":2}')""", "json"),
    ("json_quote", "JSON_QUOTE('abc')", "json"),
    ("json_contains", """JSON_CONTAINS('[1,2,3]','2')""", "json"),
    ("json_contains_path", """JSON_CONTAINS_PATH('{"a":1}','one','$.a')""", "json"),
    ("json_depth", """JSON_DEPTH('[1,[2,[3]]]')""", "json"),
    ("json_set", """JSON_SET('{"a":1}','$.b',2)""", "json"),
    ("json_insert", """JSON_INSERT('{"a":1}','$.b',2)""", "json"),
    ("json_replace", """JSON_REPLACE('{"a":1}','$.a',9)""", "json"),
    ("json_remove", """JSON_REMOVE('{"a":1,"b":2}','$.b')""", "json"),
    ("json_merge_patch", """JSON_MERGE_PATCH('{"a":1}','{"b":2}')""", "json"),
    ("json_merge_preserve", """JSON_MERGE_PRESERVE('[1]','[2]')""", "json"),
    ("json_array_append", """JSON_ARRAY_APPEND('[1,2]','$',3)""", "json"),
    ("json_array_insert", """JSON_ARRAY_INSERT('[1,3]','$[1]',2)""", "json"),
    ("json_search", """JSON_SEARCH('["a","b"]','one','b')""", "json"),
    ("json_overlaps", """JSON_OVERLAPS('[1,2]','[2,3]')""", "json"),
    ("json_pretty", """JSON_PRETTY('{"a":1}')""", "json"),
    ("json_storage_size", """JSON_STORAGE_SIZE('{"a":1}')""", "json"),
    # --- network / encoding ---
    ("inet_aton", "INET_ATON('127.0.0.1')", "network"),
    ("inet_ntoa", "INET_NTOA(2130706433)", "network"),
    ("inet6_aton", "INET6_ATON('::1')", "network"),
    ("uuid_fn", "UUID()", "misc"),
    ("uuid_short", "UUID_SHORT()", "misc"),
    ("compress", "COMPRESS('abc')", "misc"),
    ("connection_id", "CONNECTION_ID()", "misc"),
    ("database_fn", "DATABASE()", "misc"),
    ("user_fn", "USER()", "misc"),
    ("current_user", "CURRENT_USER()", "misc"),
    ("session_user", "SESSION_USER()", "misc"),
    ("version_fn", "VERSION()", "misc"),
    ("benchmark", "BENCHMARK(1,1+1)", "misc"),
    ("row_count", "ROW_COUNT()", "misc"),
    ("found_rows", "FOUND_ROWS()", "misc"),
    ("last_insert_id", "LAST_INSERT_ID()", "misc"),
    ("schema_fn", "SCHEMA()", "misc"),
    ("default_fn", "DEFAULT(1)", "misc"),
    ("values_fn", "GET_LOCK('x',0)", "misc"),
    ("release_lock", "RELEASE_LOCK('x')", "misc"),
    ("is_free_lock", "IS_FREE_LOCK('x')", "misc"),
    ("sleep_zero", "SLEEP(0)", "misc"),
    ("uuid_to_bin", "UUID_TO_BIN('00000000-0000-0000-0000-000000000001')", "misc"),
    ("bin_to_uuid", "BIN_TO_UUID(UNHEX('00000000000000000000000000000001'))", "misc"),
    ("is_uuid", "IS_UUID('00000000-0000-0000-0000-000000000001')", "misc"),
    # --- extra string functions / value variants ---
    ("concat_num", "CONCAT(1, 2, 3)", "string"),
    ("substring_index", "SUBSTRING_INDEX('a.b.c.d', '.', 2)", "string"),
    ("substring_neg", "SUBSTRING('abcdef', -3)", "string"),
    ("locate_pos", "LOCATE('b', 'abcabc', 3)", "string"),
    ("lpad_long", "LPAD('abc', 10, '*')", "string"),
    ("rpad_long", "RPAD('abc', 10, '*')", "string"),
    ("trim_both", "TRIM(BOTH 'x' FROM 'xxhixx')", "string"),
    ("trim_leading", "TRIM(LEADING 'x' FROM 'xxhi')", "string"),
    ("trim_trailing", "TRIM(TRAILING 'x' FROM 'hixx')", "string"),
    ("make_set", "MAKE_SET(5, 'a', 'b', 'c')", "string"),
    ("export_set", "EXPORT_SET(5, 'Y', 'N', ',', 4)", "string"),
    ("weight_string", "WEIGHT_STRING('abc')", "string"),
    ("char_using", "CHAR(72, 105 USING utf8mb4)", "string"),
    ("find_in_set", "FIND_IN_SET('b', 'a,b,c')", "string"),
    ("regexp_count", "REGEXP_INSTR('aXbXc', 'X')", "string"),
    # --- extra math value variants ---
    ("round_neg", "ROUND(12345.678, -2)", "math"),
    ("truncate_neg", "TRUNCATE(12345.678, -2)", "math"),
    ("mod_zero", "MOD(10, 0)", "math"),
    ("pow_frac", "POW(2, 0.5)", "math"),
    ("log_base", "LOG(2, 8)", "math"),
    ("least_str", "LEAST('b', 'a', 'c')", "math"),
    ("greatest_str", "GREATEST('b', 'a', 'c')", "math"),
    ("abs_decimal", "ABS(-12.5)", "math"),
    ("rand_in_range", "FLOOR(RAND() * 100)", "math"),
    ("crc32_num", "CRC32(12345)", "math"),
    # --- extra date variants ---
    ("date_add_hour", "DATE_ADD('2026-06-23 10:00:00', INTERVAL 5 HOUR)", "datetime"),
    ("date_add_minute", "DATE_ADD('2026-06-23 10:00:00', INTERVAL 30 MINUTE)", "datetime"),
    ("date_add_week", "DATE_ADD('2026-06-23', INTERVAL 2 WEEK)", "datetime"),
    ("date_add_year", "DATE_ADD('2026-06-23', INTERVAL 1 YEAR)", "datetime"),
    ("date_sub_day", "DATE_SUB('2026-06-23', INTERVAL 10 DAY)", "datetime"),
    ("timestampdiff_hour", "TIMESTAMPDIFF(HOUR, '2026-06-23 00:00:00', '2026-06-23 12:00:00')", "datetime"),
    ("timestampdiff_month", "TIMESTAMPDIFF(MONTH, '2026-01-01', '2026-06-23')", "datetime"),
    ("datediff_neg", "DATEDIFF('2026-06-01', '2026-06-23')", "datetime"),
    ("week_mode", "WEEK('2026-06-23', 3)", "datetime"),
    ("yearweek", "YEARWEEK('2026-06-23')", "datetime"),
    ("get_format", "GET_FORMAT(DATE, 'ISO')", "datetime"),
    ("dayofweek_sun", "DAYOFWEEK('2026-06-21')", "datetime"),
    # --- coalesce / control variants ---
    ("coalesce_first", "COALESCE('a', NULL, 'b')", "control"),
    ("greatest_null", "IFNULL(GREATEST(1,2), 0)", "control"),
    ("if_nested", "IF(1>2, 'a', IF(3>2, 'b', 'c'))", "control"),
    ("case_multi", "CASE WHEN 1=2 THEN 'x' WHEN 2=2 THEN 'y' ELSE 'z' END", "control"),
    ("nullif_eq", "NULLIF('a', 'a')", "control"),
    ("interval_fn", "INTERVAL(5, 1, 3, 7, 9)", "control"),
    # --- additional string functions ---
    ("concat_ws_many", "CONCAT_WS(',', 'a', 'b', 'c', 'd')", "string"),
    ("lcase", "LCASE('ABC')", "string"),
    ("ucase", "UCASE('abc')", "string"),
    ("mid", "MID('abcdef', 2, 3)", "string"),
    ("char_length2", "CHAR_LENGTH('test')", "string"),
    ("bit_length", "BIT_LENGTH('abc')", "string"),
    ("to_days_str", "TO_DAYS('2026-06-23')", "string"),
    ("hex_str_fn", "HEX('abc')", "string"),
    ("unhex_str", "UNHEX('616263')", "string"),
    ("ascii_a", "ASCII('a')", "string"),
    ("repeat_long", "REPEAT('=', 20)", "string"),
    ("reverse_long", "REVERSE('abcdefgh')", "string"),
    ("space_fn", "SPACE(5)", "string"),
    ("substring_from", "SUBSTRING('abcdef' FROM 2)", "string"),
    ("substring_for", "SUBSTRING('abcdef' FROM 2 FOR 3)", "string"),
    ("locate3", "LOCATE('a', 'banana', 2)", "string"),
    ("regexp_replace_g", "REGEXP_REPLACE('a1b2c3', '[0-9]', 'X')", "string"),
    ("regexp_substr2", "REGEXP_SUBSTR('abc123def', '[0-9]+')", "string"),
    # --- additional math functions ---
    ("greatest_many", "GREATEST(1, 5, 3, 9, 2)", "math"),
    ("least_many", "LEAST(5, 1, 3, 9, 2)", "math"),
    ("abs_zero", "ABS(0)", "math"),
    ("sign_pos", "SIGN(42)", "math"),
    ("sign_zero", "SIGN(0)", "math"),
    ("ceiling2", "CEILING(-4.2)", "math"),
    ("floor_neg", "FLOOR(-4.2)", "math"),
    ("round0", "ROUND(3.14159)", "math"),
    ("round3", "ROUND(3.14159, 3)", "math"),
    ("sqrt2", "SQRT(2)", "math"),
    ("exp0", "EXP(0)", "math"),
    ("ln_e", "LN(EXP(1))", "math"),
    ("degrees_pi", "DEGREES(PI())", "math"),
    ("radians_90", "RADIANS(90)", "math"),
    ("cot2", "COT(0.5)", "math"),
    ("atan2_2", "ATAN2(1, 0)", "math"),
    ("truncate0", "TRUNCATE(3.999, 0)", "math"),
    ("conv_bin", "CONV(255, 10, 2)", "math"),
    ("conv_hex", "CONV(255, 10, 16)", "math"),
    # --- additional date functions ---
    ("now0", "NOW(0)", "datetime"),
    ("now6", "NOW(6)", "datetime"),
    ("curdate2", "CURRENT_DATE", "datetime"),
    ("curtime2", "CURRENT_TIME", "datetime"),
    ("localtime_fn", "LOCALTIME()", "datetime"),
    ("localtimestamp_fn", "LOCALTIMESTAMP()", "datetime"),
    ("dayofyear2", "DAYOFYEAR('2026-12-31')", "datetime"),
    ("weekday", "WEEKDAY('2026-06-23')", "datetime"),
    ("week0", "WEEK('2026-06-23', 0)", "datetime"),
    ("week1", "WEEK('2026-06-23', 1)", "datetime"),
    ("quarter4", "QUARTER('2026-12-23')", "datetime"),
    ("time_format", "TIME_FORMAT('14:05:09', '%H:%i')", "datetime"),
    ("addtime_dt", "ADDTIME('2026-06-23 10:00:00', '02:30:00')", "datetime"),
    ("date_diff_self", "DATEDIFF('2026-06-23', '2026-06-23')", "datetime"),
    ("from_unixtime0", "FROM_UNIXTIME(0)", "datetime"),
    ("unix_timestamp0", "UNIX_TIMESTAMP()", "datetime"),
    ("makedate2", "MAKEDATE(2026, 1)", "datetime"),
    ("maketime2", "MAKETIME(25, 0, 0)", "datetime"),
    # --- additional json functions ---
    ("json_object_nested", """JSON_OBJECT('a', JSON_OBJECT('b', 1))""", "json"),
    ("json_array_nested", "JSON_ARRAY(1, JSON_ARRAY(2, 3))", "json"),
    ("json_extract_arr", """JSON_EXTRACT('[10,20,30]', '$[1]')""", "json"),
    ("json_extract_wild", """JSON_EXTRACT('{"a":{"b":1}}', '$.a.b')""", "json"),
    ("json_unquote_obj", """JSON_UNQUOTE(JSON_EXTRACT('{"k":"v"}', '$.k'))""", "json"),
    ("json_merge", """JSON_MERGE('[1]', '[2]')""", "json"),
    ("member_of", """1 MEMBER OF('[1,2,3]')""", "json"),
    # --- final batch: more string/math/date/misc scalar functions ---
    ("elt2", "ELT(1, 'a', 'b', 'c')", "string"),
    ("field2", "FIELD('c', 'a', 'b', 'c')", "string"),
    ("export_set2", "EXPORT_SET(3, '1', '0')", "string"),
    ("insert_fn2", "INSERT('Quadratic', 3, 4, 'What')", "string"),
    ("char_no_using", "CHAR(77, 121, 83, 81, 76)", "string"),
    ("format_locale", "FORMAT(12332.1234567, 4)", "string"),
    ("hex_num2", "HEX(1234)", "string"),
    ("bin2", "BIN(255)", "string"),
    ("oct2", "OCT(255)", "string"),
    ("ascii2", "ASCII('z')", "string"),
    ("space2", "SPACE(0)", "string"),
    ("repeat0", "REPEAT('x', 0)", "string"),
    ("ln1", "LN(1)", "math"),
    ("log_neg", "LOG(10, 100)", "math"),
    ("pow_zero", "POW(5, 0)", "math"),
    ("sqrt_zero", "SQRT(0)", "math"),
    ("mod_negative", "MOD(-7, 3)", "math"),
    ("round_negative_prec", "ROUND(1234.5678, -1)", "math"),
    ("truncate_int", "TRUNCATE(1234, -2)", "math"),
    ("abs_float", "ABS(-3.14159)", "math"),
    ("sign_negative", "SIGN(-99)", "math"),
    ("cos_pi", "COS(PI())", "math"),
    ("sin_half_pi", "SIN(PI()/2)", "math"),
    ("tan_zero", "TAN(0)", "math"),
    ("now_neg_paren", "NOW() + INTERVAL 0 SECOND", "datetime"),
    ("date_format_full", "DATE_FORMAT('2026-06-23','%W, %M %e, %Y')", "datetime"),
    ("str_to_date_time", "STR_TO_DATE('14:05:09', '%H:%i:%s')", "datetime"),
    ("dayname2", "DAYNAME('2026-01-01')", "datetime"),
    ("monthname2", "MONTHNAME('2026-12-01')", "datetime"),
    ("last_day_feb", "LAST_DAY('2026-02-15')", "datetime"),
    ("timestampadd_hour", "TIMESTAMPADD(HOUR, 5, '2026-06-23 00:00:00')", "datetime"),
    ("addtime2", "ADDTIME('10:00:00', '00:30:00')", "datetime"),
    ("convert_tz2", "CONVERT_TZ('2026-06-23 12:00:00', 'SYSTEM', '+09:00')", "datetime"),
    ("if_else_chain", "IF(0, 'a', IF(0, 'b', 'c'))", "control"),
    ("ifnull_nested", "IFNULL(IFNULL(NULL, NULL), 'x')", "control"),
    ("coalesce_mixed", "COALESCE(NULL, 0, 'a')", "control"),
]

# Aggregate / window functions: (label, expr_over_col, supports_window)
AGGREGATES: list[tuple[str, str, bool]] = [
    ("count", "COUNT({c})", True),
    ("count_star", "COUNT(*)", True),
    ("count_distinct", "COUNT(DISTINCT {c})", False),
    ("sum", "SUM({c})", True),
    ("avg", "AVG({c})", True),
    ("min", "MIN({c})", True),
    ("max", "MAX({c})", True),
    ("group_concat", "GROUP_CONCAT({c})", False),
    ("std", "STD({c})", False),
    ("stddev", "STDDEV({c})", False),
    ("stddev_pop", "STDDEV_POP({c})", False),
    ("stddev_samp", "STDDEV_SAMP({c})", False),
    ("variance", "VARIANCE({c})", False),
    ("var_pop", "VAR_POP({c})", False),
    ("var_samp", "VAR_SAMP({c})", False),
    ("bit_and_agg", "BIT_AND({c})", False),
    ("bit_or_agg", "BIT_OR({c})", False),
    ("bit_xor_agg", "BIT_XOR({c})", False),
]

WINDOW_FUNCS: list[tuple[str, str]] = [
    ("row_number", "ROW_NUMBER()"),
    ("rank", "RANK()"),
    ("dense_rank", "DENSE_RANK()"),
    ("percent_rank", "PERCENT_RANK()"),
    ("cume_dist", "CUME_DIST()"),
    ("ntile", "NTILE(2)"),
    ("lag", "LAG({c})"),
    ("lead", "LEAD({c})"),
    ("first_value", "FIRST_VALUE({c})"),
    ("last_value", "LAST_VALUE({c})"),
    ("nth_value", "NTH_VALUE({c},2)"),
]
