'use strict';

// ---------------------------------------------------------------------------
// Shared test-matrix definitions used to *generate* thousands of scenarios.
// Each definition pairs a column type with sample values so a single loop can
// emit declare / insert / roundtrip / null / boundary / update / where / order
// / group / index scenarios. Nothing here assumes MatrixOne succeeds — the
// runner records whatever happens.
// ---------------------------------------------------------------------------

// SQL data types for the raw / DDL matrix. `sample` is a representative value;
// `boundary` is an extreme value; `nullable` indicates a NULL test makes sense.
const SQL_TYPES = [
  { name: 'tinyint', sql: 'TINYINT', sample: 7, boundary: 127, group: 'int' },
  { name: 'tinyint_u', sql: 'TINYINT UNSIGNED', sample: 200, boundary: 255, group: 'int' },
  { name: 'smallint', sql: 'SMALLINT', sample: 1234, boundary: 32767, group: 'int' },
  { name: 'mediumint', sql: 'MEDIUMINT', sample: 100000, boundary: 8388607, group: 'int' },
  { name: 'int', sql: 'INT', sample: 42, boundary: 2147483647, group: 'int' },
  { name: 'int_u', sql: 'INT UNSIGNED', sample: 42, boundary: 4294967295, group: 'int' },
  { name: 'bigint', sql: 'BIGINT', sample: 9007199254740991, boundary: 9223372036854775807n, group: 'int' },
  { name: 'bigint_u', sql: 'BIGINT UNSIGNED', sample: 100, boundary: 18446744073709551615n, group: 'int' },
  { name: 'decimal', sql: 'DECIMAL(18,4)', sample: '12345.6789', boundary: '99999999999999.9999', group: 'num' },
  { name: 'numeric', sql: 'NUMERIC(10,2)', sample: '99.99', boundary: '99999999.99', group: 'num' },
  { name: 'float', sql: 'FLOAT', sample: 3.5, boundary: 3.4028e38, group: 'num' },
  { name: 'float_ps', sql: 'FLOAT(10,2)', sample: 3.5, boundary: 12345.67, group: 'num' },
  { name: 'double', sql: 'DOUBLE', sample: 3.141592653589793, boundary: 1.7976e308, group: 'num' },
  { name: 'real', sql: 'REAL', sample: 2.718281828, boundary: 1.5e100, group: 'num' },
  { name: 'bit', sql: 'BIT(8)', sample: null, boundary: null, group: 'bit', skipValue: true },
  { name: 'bool', sql: 'BOOL', sample: 1, boundary: 0, group: 'int' },
  { name: 'boolean', sql: 'BOOLEAN', sample: 1, boundary: 0, group: 'int' },
  { name: 'char', sql: 'CHAR(10)', sample: 'abc', boundary: '0123456789', group: 'str' },
  { name: 'varchar', sql: 'VARCHAR(255)', sample: 'hello world', boundary: 'x'.repeat(255), group: 'str' },
  { name: 'tinytext', sql: 'TINYTEXT', sample: 'tiny', boundary: 'y'.repeat(255), group: 'str' },
  { name: 'text', sql: 'TEXT', sample: 'some text', boundary: 'z'.repeat(1000), group: 'str' },
  { name: 'mediumtext', sql: 'MEDIUMTEXT', sample: 'medium', boundary: 'm'.repeat(2000), group: 'str' },
  { name: 'longtext', sql: 'LONGTEXT', sample: 'long', boundary: 'l'.repeat(5000), group: 'str' },
  { name: 'binary', sql: 'BINARY(16)', sample: Buffer.from('0123456789abcdef'), boundary: Buffer.alloc(16, 0xff), group: 'bin' },
  { name: 'varbinary', sql: 'VARBINARY(255)', sample: Buffer.from('blob-data'), boundary: Buffer.alloc(255, 1), group: 'bin' },
  { name: 'tinyblob', sql: 'TINYBLOB', sample: Buffer.from('tiny'), boundary: Buffer.alloc(255, 2), group: 'bin' },
  { name: 'blob', sql: 'BLOB', sample: Buffer.from('blobby'), boundary: Buffer.alloc(1024, 3), group: 'bin' },
  { name: 'mediumblob', sql: 'MEDIUMBLOB', sample: Buffer.from('mblob'), boundary: Buffer.alloc(2048, 4), group: 'bin' },
  { name: 'longblob', sql: 'LONGBLOB', sample: Buffer.from('lblob'), boundary: Buffer.alloc(4096, 5), group: 'bin' },
  { name: 'date', sql: 'DATE', sample: '2026-06-23', boundary: '9999-12-31', group: 'dt' },
  { name: 'time', sql: 'TIME', sample: '11:30:00', boundary: '23:59:59', group: 'dt' },
  { name: 'datetime', sql: 'DATETIME', sample: '2026-06-23 11:30:00', boundary: '9999-12-31 23:59:59', group: 'dt' },
  { name: 'timestamp', sql: 'TIMESTAMP', sample: '2026-06-23 11:30:00', boundary: '2038-01-19 03:14:07', group: 'dt' },
  { name: 'year', sql: 'YEAR', sample: 2026, boundary: 2155, group: 'dt' },
  { name: 'enum', sql: "ENUM('a','b','c')", sample: 'b', boundary: 'c', group: 'enum' },
  { name: 'set', sql: "SET('a','b','c')", sample: 'a,b', boundary: 'a,b,c', group: 'enum' },
  { name: 'json', sql: 'JSON', sample: JSON.stringify({ k: 'v', n: 1 }), boundary: JSON.stringify([1, 2, 3]), group: 'json' },
  { name: 'uuid', sql: 'UUID', sample: null, boundary: null, group: 'uuid', skipValue: true },
  { name: 'vecf32', sql: 'VECF32(3)', sample: '[1,2,3]', boundary: '[0,0,0]', group: 'vector' },
  { name: 'vecf64', sql: 'VECF64(3)', sample: '[1,2,3]', boundary: '[9,9,9]', group: 'vector' },
];

// Scalar SQL functions for the function matrix. expr uses literal args so each
// can be tested in a bare SELECT. category groups them in the report.
const SQL_FUNCTIONS = [
  // string
  ['string', 'CONCAT', "CONCAT('a','b','c')"],
  ['string', 'CONCAT_WS', "CONCAT_WS('-','a','b')"],
  ['string', 'LENGTH', "LENGTH('abc')"],
  ['string', 'CHAR_LENGTH', "CHAR_LENGTH('abc')"],
  ['string', 'CHARACTER_LENGTH', "CHARACTER_LENGTH('abc')"],
  ['string', 'OCTET_LENGTH', "OCTET_LENGTH('abc')"],
  ['string', 'BIT_LENGTH', "BIT_LENGTH('abc')"],
  ['string', 'LOWER', "LOWER('ABC')"],
  ['string', 'UPPER', "UPPER('abc')"],
  ['string', 'LCASE', "LCASE('ABC')"],
  ['string', 'UCASE', "UCASE('abc')"],
  ['string', 'SUBSTRING', "SUBSTRING('abcdef',2,3)"],
  ['string', 'SUBSTR', "SUBSTR('abcdef',2,3)"],
  ['string', 'MID', "MID('abcdef',2,3)"],
  ['string', 'LEFT', "LEFT('abcdef',2)"],
  ['string', 'RIGHT', "RIGHT('abcdef',2)"],
  ['string', 'TRIM', "TRIM(' abc ')"],
  ['string', 'LTRIM', "LTRIM(' abc')"],
  ['string', 'RTRIM', "RTRIM('abc ')"],
  ['string', 'LPAD', "LPAD('abc',5,'*')"],
  ['string', 'RPAD', "RPAD('abc',5,'*')"],
  ['string', 'REPLACE', "REPLACE('abcabc','a','X')"],
  ['string', 'REVERSE', "REVERSE('abc')"],
  ['string', 'REPEAT', "REPEAT('ab',3)"],
  ['string', 'SPACE', "SPACE(3)"],
  ['string', 'LOCATE', "LOCATE('b','abc')"],
  ['string', 'POSITION', "POSITION('b' IN 'abc')"],
  ['string', 'INSTR', "INSTR('abc','b')"],
  ['string', 'FIELD', "FIELD('b','a','b','c')"],
  ['string', 'FIND_IN_SET', "FIND_IN_SET('b','a,b,c')"],
  ['string', 'ELT', "ELT(2,'a','b','c')"],
  ['string', 'INSERT', "INSERT('abcdef',2,2,'XY')"],
  ['string', 'ASCII', "ASCII('A')"],
  ['string', 'ORD', "ORD('A')"],
  ['string', 'CHAR', "CHAR(65)"],
  ['string', 'HEX', "HEX('abc')"],
  ['string', 'UNHEX', "UNHEX('616263')"],
  ['string', 'TO_BASE64', "TO_BASE64('abc')"],
  ['string', 'FROM_BASE64', "FROM_BASE64('YWJj')"],
  ['string', 'QUOTE', "QUOTE('abc')"],
  ['string', 'SOUNDEX', "SOUNDEX('Robert')"],
  ['string', 'FORMAT', "FORMAT(1234.567,2)"],
  ['string', 'CONV', "CONV('FF',16,10)"],
  ['string', 'WEIGHT_STRING', "WEIGHT_STRING('abc')"],
  ['string', 'EXPORT_SET', "EXPORT_SET(5,'Y','N',',',4)"],
  ['string', 'MAKE_SET', "MAKE_SET(1|4,'a','b','c')"],
  ['string', 'REGEXP_REPLACE', "REGEXP_REPLACE('abc','b','X')"],
  ['string', 'REGEXP_SUBSTR', "REGEXP_SUBSTR('abc','b')"],
  ['string', 'REGEXP_INSTR', "REGEXP_INSTR('abc','b')"],
  ['string', 'REGEXP_LIKE', "REGEXP_LIKE('abc','b')"],
  // numeric
  ['numeric', 'ABS', "ABS(-5)"],
  ['numeric', 'CEIL', "CEIL(4.2)"],
  ['numeric', 'CEILING', "CEILING(4.2)"],
  ['numeric', 'FLOOR', "FLOOR(4.8)"],
  ['numeric', 'ROUND', "ROUND(4.567,2)"],
  ['numeric', 'TRUNCATE', "TRUNCATE(4.567,2)"],
  ['numeric', 'MOD', "MOD(10,3)"],
  ['numeric', 'POW', "POW(2,10)"],
  ['numeric', 'POWER', "POWER(2,10)"],
  ['numeric', 'SQRT', "SQRT(16)"],
  ['numeric', 'EXP', "EXP(1)"],
  ['numeric', 'LN', "LN(2.718281828)"],
  ['numeric', 'LOG', "LOG(2.718281828)"],
  ['numeric', 'LOG2', "LOG2(8)"],
  ['numeric', 'LOG10', "LOG10(1000)"],
  ['numeric', 'SIN', "SIN(0)"],
  ['numeric', 'COS', "COS(0)"],
  ['numeric', 'TAN', "TAN(0)"],
  ['numeric', 'ASIN', "ASIN(0)"],
  ['numeric', 'ACOS', "ACOS(1)"],
  ['numeric', 'ATAN', "ATAN(1)"],
  ['numeric', 'ATAN2', "ATAN2(1,1)"],
  ['numeric', 'COT', "COT(1)"],
  ['numeric', 'DEGREES', "DEGREES(3.14159)"],
  ['numeric', 'RADIANS', "RADIANS(180)"],
  ['numeric', 'PI', "PI()"],
  ['numeric', 'SIGN', "SIGN(-3)"],
  ['numeric', 'RAND', "FLOOR(RAND()*0)"],
  ['numeric', 'CRC32', "CRC32('abc')"],
  ['numeric', 'GREATEST', "GREATEST(1,5,3)"],
  ['numeric', 'LEAST', "LEAST(1,5,3)"],
  ['numeric', 'BIT_COUNT', "BIT_COUNT(7)"],
  // date/time
  ['datetime', 'NOW', "DATE(NOW())"],
  ['datetime', 'CURDATE', "DATE(CURDATE())"],
  ['datetime', 'CURRENT_DATE', "DATE(CURRENT_DATE)"],
  ['datetime', 'CURTIME', "CURTIME() IS NOT NULL"],
  ['datetime', 'CURRENT_TIMESTAMP', "CURRENT_TIMESTAMP() IS NOT NULL"],
  ['datetime', 'UNIX_TIMESTAMP', "UNIX_TIMESTAMP('2026-01-01 00:00:00')>0"],
  ['datetime', 'FROM_UNIXTIME', "FROM_UNIXTIME(0) IS NOT NULL"],
  ['datetime', 'DATE', "DATE('2026-06-23 11:00:00')"],
  ['datetime', 'TIME', "TIME('2026-06-23 11:00:00')"],
  ['datetime', 'YEAR', "YEAR('2026-06-23')"],
  ['datetime', 'MONTH', "MONTH('2026-06-23')"],
  ['datetime', 'DAY', "DAY('2026-06-23')"],
  ['datetime', 'DAYOFMONTH', "DAYOFMONTH('2026-06-23')"],
  ['datetime', 'DAYOFWEEK', "DAYOFWEEK('2026-06-23')"],
  ['datetime', 'DAYOFYEAR', "DAYOFYEAR('2026-06-23')"],
  ['datetime', 'WEEKDAY', "WEEKDAY('2026-06-23')"],
  ['datetime', 'WEEK', "WEEK('2026-06-23')"],
  ['datetime', 'WEEKOFYEAR', "WEEKOFYEAR('2026-06-23')"],
  ['datetime', 'QUARTER', "QUARTER('2026-06-23')"],
  ['datetime', 'HOUR', "HOUR('11:30:00')"],
  ['datetime', 'MINUTE', "MINUTE('11:30:00')"],
  ['datetime', 'SECOND', "SECOND('11:30:45')"],
  ['datetime', 'MICROSECOND', "MICROSECOND('11:30:45.123456')"],
  ['datetime', 'DAYNAME', "DAYNAME('2026-06-23')"],
  ['datetime', 'MONTHNAME', "MONTHNAME('2026-06-23')"],
  ['datetime', 'LAST_DAY', "LAST_DAY('2026-06-23')"],
  ['datetime', 'DATE_ADD', "DATE_ADD('2026-06-23', INTERVAL 1 DAY)"],
  ['datetime', 'DATE_SUB', "DATE_SUB('2026-06-23', INTERVAL 1 DAY)"],
  ['datetime', 'ADDDATE', "ADDDATE('2026-06-23', 1)"],
  ['datetime', 'SUBDATE', "SUBDATE('2026-06-23', 1)"],
  ['datetime', 'DATEDIFF', "DATEDIFF('2026-06-24','2026-06-23')"],
  ['datetime', 'TIMEDIFF', "TIMEDIFF('11:00:00','10:00:00')"],
  ['datetime', 'TIMESTAMPDIFF', "TIMESTAMPDIFF(DAY,'2026-06-23','2026-06-24')"],
  ['datetime', 'TIMESTAMPADD', "TIMESTAMPADD(DAY,1,'2026-06-23')"],
  ['datetime', 'DATE_FORMAT', "DATE_FORMAT('2026-06-23','%Y/%m/%d')"],
  ['datetime', 'STR_TO_DATE', "STR_TO_DATE('2026-06-23','%Y-%m-%d')"],
  ['datetime', 'EXTRACT', "EXTRACT(YEAR FROM '2026-06-23')"],
  ['datetime', 'SEC_TO_TIME', "SEC_TO_TIME(3661)"],
  ['datetime', 'TIME_TO_SEC', "TIME_TO_SEC('01:01:01')"],
  ['datetime', 'MAKEDATE', "MAKEDATE(2026,1)"],
  ['datetime', 'MAKETIME', "MAKETIME(1,1,1)"],
  ['datetime', 'PERIOD_ADD', "PERIOD_ADD(202601,1)"],
  ['datetime', 'PERIOD_DIFF', "PERIOD_DIFF(202602,202601)"],
  ['datetime', 'TO_DAYS', "TO_DAYS('2026-06-23')"],
  ['datetime', 'FROM_DAYS', "FROM_DAYS(739000)"],
  ['datetime', 'UTC_DATE', "UTC_DATE() IS NOT NULL"],
  ['datetime', 'UTC_TIME', "UTC_TIME() IS NOT NULL"],
  ['datetime', 'UTC_TIMESTAMP', "UTC_TIMESTAMP() IS NOT NULL"],
  ['datetime', 'ADDTIME', "ADDTIME('11:00:00','01:00:00')"],
  ['datetime', 'SUBTIME', "SUBTIME('11:00:00','01:00:00')"],
  // control / misc
  ['misc', 'IF', "IF(1>0,'y','n')"],
  ['misc', 'IFNULL', "IFNULL(NULL,'x')"],
  ['misc', 'NULLIF', "NULLIF(1,1)"],
  ['misc', 'COALESCE', "COALESCE(NULL,NULL,3)"],
  ['misc', 'ISNULL', "ISNULL(NULL)"],
  ['misc', 'CASE', "CASE WHEN 1>0 THEN 'a' ELSE 'b' END"],
  ['misc', 'GREATEST_STR', "GREATEST('a','b')"],
  ['misc', 'INET_ATON', "INET_ATON('1.2.3.4')"],
  ['misc', 'INET_NTOA', "INET_NTOA(16909060)"],
  ['misc', 'INET6_ATON', "HEX(INET6_ATON('::1'))"],
  ['misc', 'UUID', "UUID() IS NOT NULL"],
  ['misc', 'UUID_SHORT', "UUID_SHORT()>0"],
  ['misc', 'BIN', "BIN(7)"],
  ['misc', 'OCT', "OCT(8)"],
  ['misc', 'MD5', "MD5('abc')"],
  ['misc', 'SHA', "SHA('abc')"],
  ['misc', 'SHA1', "SHA1('abc')"],
  ['misc', 'SHA2', "SHA2('abc',256)"],
  ['misc', 'COMPRESS', "LENGTH(COMPRESS('abc'))>0"],
  ['misc', 'BENCHMARK', "BENCHMARK(1,1)"],
  // json
  ['json', 'JSON_EXTRACT', "JSON_EXTRACT('{\"a\":1}','$.a')"],
  ['json', 'JSON_VALID', "JSON_VALID('{}')"],
  ['json', 'JSON_OBJECT', "JSON_OBJECT('a',1)"],
  ['json', 'JSON_ARRAY', "JSON_ARRAY(1,2)"],
  ['json', 'JSON_QUOTE', "JSON_QUOTE('a')"],
  ['json', 'JSON_UNQUOTE', "JSON_UNQUOTE('\"a\"')"],
  ['json', 'JSON_KEYS', "JSON_KEYS('{\"a\":1}')"],
  ['json', 'JSON_LENGTH', "JSON_LENGTH('[1,2,3]')"],
  ['json', 'JSON_TYPE', "JSON_TYPE('[]')"],
  ['json', 'JSON_DEPTH', "JSON_DEPTH('[1,[2]]')"],
  ['json', 'JSON_SET', "JSON_SET('{}','$.a',1)"],
  ['json', 'JSON_INSERT', "JSON_INSERT('{}','$.a',1)"],
  ['json', 'JSON_REPLACE', "JSON_REPLACE('{\"a\":1}','$.a',2)"],
  ['json', 'JSON_REMOVE', "JSON_REMOVE('{\"a\":1,\"b\":2}','$.a')"],
  ['json', 'JSON_CONTAINS', "JSON_CONTAINS('[1,2]','1')"],
  ['json', 'JSON_CONTAINS_PATH', "JSON_CONTAINS_PATH('{\"a\":1}','one','$.a')"],
  ['json', 'JSON_SEARCH', "JSON_SEARCH('{\"a\":\"x\"}','one','x')"],
  ['json', 'JSON_MERGE_PATCH', "JSON_MERGE_PATCH('{\"a\":1}','{\"b\":2}')"],
  ['json', 'JSON_MERGE_PRESERVE', "JSON_MERGE_PRESERVE('[1]','[2]')"],
  ['json', 'JSON_ARRAY_APPEND', "JSON_ARRAY_APPEND('[1]','$',2)"],
  ['json', 'JSON_ARRAY_INSERT', "JSON_ARRAY_INSERT('[1,2]','$[0]',0)"],
  ['json', 'JSON_OVERLAPS', "JSON_OVERLAPS('[1,2]','[2,3]')"],
  ['json', 'JSON_PRETTY', "JSON_PRETTY('{\"a\":1}')"],
  ['json', 'JSON_STORAGE_SIZE', "JSON_STORAGE_SIZE('{}')"],
  // aggregate/window-ish (wrapped so they run standalone via a subselect-free form)
  ['aggregate', 'STDDEV', "STDDEV(1)"],
  ['aggregate', 'STDDEV_POP', "STDDEV_POP(1)"],
  ['aggregate', 'STDDEV_SAMP', "STDDEV_SAMP(1)"],
  ['aggregate', 'VARIANCE', "VARIANCE(1)"],
  ['aggregate', 'VAR_POP', "VAR_POP(1)"],
  ['aggregate', 'VAR_SAMP', "VAR_SAMP(1)"],
  ['aggregate', 'BIT_AND', "BIT_AND(7)"],
  ['aggregate', 'BIT_OR', "BIT_OR(1)"],
  ['aggregate', 'BIT_XOR', "BIT_XOR(1)"],
  // spatial
  ['spatial', 'ST_GeomFromText', "ST_GeomFromText('POINT(1 1)') IS NOT NULL"],
  ['spatial', 'POINT', "POINT(1,1) IS NOT NULL"],
  ['spatial', 'ST_X', "ST_X(POINT(1,2))"],
  ['spatial', 'ST_Y', "ST_Y(POINT(1,2))"],
  ['spatial', 'ST_AsText', "ST_AsText(POINT(1,1))"],
  ['spatial', 'ST_Distance', "ST_Distance(POINT(0,0),POINT(3,4))"],
];

// Query operators for the Sequelize Op.* / TypeORM / Knex where matrix.
const WHERE_OPS = [
  'eq', 'ne', 'gt', 'gte', 'lt', 'lte', 'in', 'notIn',
  'like', 'notLike', 'between', 'notBetween', 'isNull', 'notNull',
  'and', 'or', 'not',
];

// Relationship kinds for the association matrix.
const RELATIONS = ['hasOne', 'belongsTo', 'hasMany', 'belongsToMany'];

// Batch sizes for the workload matrix.
const BATCH_SIZES = [1, 10, 100, 1000];

module.exports = {
  SQL_TYPES,
  SQL_FUNCTIONS,
  WHERE_OPS,
  RELATIONS,
  BATCH_SIZES,
};
